#!/usr/bin/env bash
#|-------------+----------------------------------------------------------|
#| Title       | ifconfig-me                                              |
#|-------------+----------------------------------------------------------|
#| Date        | 2010-11-16                                               |
#|-------------+----------------------------------------------------------|
#| Author      | Israel Fimbres D. <israel.fimbres@gmail.com>             |
#|-------------+----------------------------------------------------------|
#| Version     | 1.0                                                      |
#|-------------+----------------------------------------------------------|
#| Description | Client who exposes some of the services of the           |
#|             | <http://ifconfig.me> site to the command line interface. |
#|-------------+----------------------------------------------------------|

[ -z $1 ] && cat <<EOF && exit 1
ifconfig-me { -i | -u | -h | -p }

-i
  ip

-u
  user agent

-h
  host

-p
  port

EOF


if hash wget > /dev/null 2>&1 ; then
    user_agent='wget -q -O - '
elif hash curl > /dev/null 2>&1; then
    user_agent='curl '
else
    echo 'error: either wget or curl must be installed' 1>&2
    exit -1
fi

while getopts 'iuhpa:' op
do
    case $op in
	'i') $user_agent http://ifconfig.me/ip ;;
	'u') $user_agent http://ifconfig.me/ua ;;
	'h') $user_agent http://ifconfig.me/host ;;
	'p') $user_agent http://ifconfig.me/port ;;
    esac
done

exit 0
