#!/bin/bash
#|-------------+--------------------------------------------------------------|
#| Title       | thue-morse-cli                                               |
#|-------------+--------------------------------------------------------------|
#| Date        | 2011-10-03                                                   |
#|-------------+--------------------------------------------------------------|
#| Author      | Israel Fimbres D. <israel.fimbres@gmail.com>                 |
#|-------------+--------------------------------------------------------------|
#| Version     | 1.0                                                          |
#|-------------+--------------------------------------------------------------|
#| Description | Bash implementation of the Thue-Morse sequence.              |
#|             | Receives one parameter that defines the number of iterations |
#|             | we wish to run over the algorithm. If no value is proposed   |
#|             | one iteration runs by default.                               |
#|-------------+--------------------------------------------------------------|

function thue-morse
{
    local i=${1:-1}
    local x=${2:-0}
    local y=$(tr 01 10 <<< $x)

    [ $i -ne 1 ] && thue-morse $[i-1] $x$y || echo $x$y
}

function main
{
    local iterations=$1

    thue-morse $iterations
}

main $1

exit 0
